runtime: php81
env: standard

# معالج الطلبات الرئيسي
entrypoint: serve -S 0.0.0.0:8080 -t .

# معالجات المسارات
handlers:
  # الملفات الثابتة - CSS
  - url: /frontend/assets/css
    static_dir: frontend/assets/css
    secure: always

  # الملفات الثابتة - JavaScript
  - url: /frontend/assets/js
    static_dir: frontend/assets/js
    secure: always

  # صفحات Frontend
  - url: /frontend
    static_dir: frontend/pages
    secure: always

  # جميع الطلبات الأخرى تذهب لـ PHP
  - url: /.*
    script: auto
    secure: always

# متغيرات البيئة
env_variables:
  # سيتم استبدال هذه القيم بعد إنشاء Cloud SQL
  DB_HOST: "/cloudsql/YOUR_PROJECT_ID:YOUR_REGION:YOUR_INSTANCE_NAME"
  DB_USER: "root"
  DB_PASS: "YOUR_DATABASE_PASSWORD"
  DB_NAME: "amz_inventory"

# الموارد المطلوبة (F1 = المجانية)
instance_class: F1

# التوسع التلقائي
automatic_scaling:
  min_idle_instances: 0
  max_idle_instances: 1
  min_pending_latency: automatic
  max_pending_latency: 30ms
  max_concurrent_requests: 10
